package flatten

import (
	"fmt"
	"strings"
)

// Banner renders the "this file is generated" callout that is prepended to the
// output. It names the source file and the command that regenerates it, and
// tells agents to edit the source instead of the generated file.
//
// The source/output names and the regenerate command are parameterized on
// opts rather than hardcoded, so the same banner shape works for any
// --src/--out pair, not just the default AGENTS.src.md/AGENTS.md.
func Banner(opts Options) string {
	src, out := opts.srcName(), opts.outName()
	return strings.Join([]string{
		"> [!IMPORTANT]",
		"> **This file is generated. Do not edit it directly — edits here will be",
		"> overwritten.**",
		">",
		fmt.Sprintf("> Edit [`%s`](%s) instead, then regenerate:", src, src),
		fmt.Sprintf("> `at-include --src %s --out %s`", src, out),
		">",
		fmt.Sprintf("> **If you are an agent** and were asked to change `%s`, make the change", out),
		fmt.Sprintf("> in `%s` and regenerate — do not edit this file.", src),
	}, "\n")
}

// HookPreamble renders the fixed framing text prepended to --hook-mode
// output. Unlike Banner, it takes no Options: the wording never varies by
// source/output name, and there is no --marker-desc-style override for it —
// hook-mode's preamble is intentionally not configurable.
func HookPreamble() string {
	return strings.Join([]string{
		"We use `@path` import syntax in Markdown docs (e.g. `AGENTS.md`) to",
		"reference other files.",
		"",
		"Below, we've pre-expanded every `@import` found in `AGENTS.md`",
		"(recursively) so you don't need to look them up.",
		"",
		"If you encounter an `@path` reference in some other file that wasn't",
		"pre-expanded here, treat it as a pointer: go read that file yourself,",
		"since it won't be auto-resolved.",
	}, "\n")
}

// Assemble joins the banner and flattened content and normalizes the trailing
// newline run to exactly one.
//
// strings.TrimRight(s, "\n") strips however many trailing newlines are
// present (including zero), so appending "\n" afterward always leaves exactly
// one, for every input: empty content, content that is all newlines, and
// content with no trailing newline all end up the same way.
//
// The normalization is applied to the combined banner+content text rather
// than to content alone, so the single-trailing-newline invariant holds even
// when content itself is empty or consists only of newlines.
func Assemble(banner, content string) string {
	return strings.TrimRight(banner+"\n\n"+content, "\n") + "\n"
}
