package flatten

import (
	"fmt"
	"strings"
)

// Banner renders the "this file is generated" callout that is prepended to the
// output. It names the source file and the command that regenerates it, and
// tells agents to edit the source instead of the generated file.
//
// This is a deliberate generalization of the JS spec's renderBanner(), which
// hardcodes "AGENTS.src.md"/"AGENTS.md" and the "node scripts/build-agents.mjs"
// command. Everything else — the callout shape, wording, and the "If you are
// an agent" rule — matches the JS verbatim.
func Banner(opts Options) string {
	src, out := opts.SrcName, opts.OutName
	if src == "" {
		src = "AGENTS.src.md"
	}
	if out == "" {
		out = "AGENTS.md"
	}
	return strings.Join([]string{
		"> [!IMPORTANT]",
		"> **This file is generated. Do not edit it directly — edits here will be",
		"> overwritten.**",
		">",
		fmt.Sprintf("> Edit [`%s`](%s) instead, then regenerate:", src, src),
		fmt.Sprintf("> `at-include --src %s --out %s`", src, out),
		">",
		fmt.Sprintf("> **If you are an agent** and were asked to change `%s`, make the change", out),
		fmt.Sprintf("> in `%s` and regenerate — do not edit this file.", src),
	}, "\n")
}

// Assemble joins the banner and flattened content and normalizes the trailing
// newline run to exactly one.
//
// Matches the JS assembleOutput():
//
//	const assembled = renderBanner() + "\n\n" + content;
//	return assembled.replace(/\n*$/, "\n");
//
// strings.TrimRight(s, "\n") strips the same maximal trailing run of "\n"
// that the JS regex /\n*$/ matches (both operate on "however many trailing
// newlines are present, including zero"), so appending "\n" after TrimRight
// reproduces replace(/\n*$/, "\n") for every input, including empty content,
// content that is all newlines, and content with no trailing newline. Verified
// differentially against the JS (see check_test.go's TestAssembleMatchesJS).
//
// The normalization is applied to the combined text rather than to content
// alone, so the single-trailing-newline invariant holds even when content is
// empty or consists only of newlines.
func Assemble(banner, content string) string {
	return strings.TrimRight(banner+"\n\n"+content, "\n") + "\n"
}
