// Package cli tests intentionally do NOT call t.Parallel().
//
// Run's public signature (fixed by the design spec) is
// Run(argv []string, stdout, stderr io.Writer) int — it has no working-
// directory parameter, because relative --src/--out/--root paths must resolve
// against the process's actual CWD, mirroring the JS's implicit
// process.cwd()-relative resolution. Driving that from tests means calling
// os.Chdir, which mutates process-global state: two tests changing directory
// concurrently would race and could each observe the other's CWD. So every
// test in this file runs serially (the package's default, absent
// t.Parallel()), and `run` restores the previous CWD via defer before
// returning.
//
// A later task (the fixture suite under test/) execs the real compiled
// binary in its own temp directory per case, which exercises CWD-relative
// behavior end to end under real process isolation. These unit tests instead
// focus on flag parsing and wiring into the flatten package; they don't need
// to run in parallel with each other to do that.
package cli

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// writeTree creates files under a fresh temp dir and returns its path.
func writeTree(t *testing.T, files map[string]string) string {
	t.Helper()
	dir, err := filepath.EvalSymlinks(t.TempDir())
	if err != nil {
		t.Fatalf("EvalSymlinks: %v", err)
	}
	for rel, content := range files {
		abs := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			t.Fatalf("MkdirAll: %v", err)
		}
		if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
			t.Fatalf("WriteFile: %v", err)
		}
	}
	return dir
}

// run invokes Run with cwd set to dir, returning code, stdout, stderr.
func run(t *testing.T, dir string, argv ...string) (code int, stdout, stderr string) {
	t.Helper()
	prev, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("Chdir: %v", err)
	}
	defer func() { _ = os.Chdir(prev) }()

	var out, errOut bytes.Buffer
	code = Run(argv, &out, &errOut)
	return code, out.String(), errOut.String()
}

func TestRunDefaultWritesOutput(t *testing.T) {
	dir := writeTree(t, map[string]string{"AGENTS.src.md": "Body\n\n@x.md\n", "x.md": "X-CLI\n"})
	code, stdout, stderr := run(t, dir)
	if code != 0 {
		t.Fatalf("code = %d, stderr = %q", code, stderr)
	}
	const want = "Generated AGENTS.md from AGENTS.src.md (1 files inlined).\n"
	if stdout != want {
		t.Errorf("stdout = %q, want %q", stdout, want)
	}
	written, err := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !strings.HasPrefix(string(written), "> [!IMPORTANT]") || !strings.Contains(string(written), "X-CLI") {
		t.Errorf("written output looks wrong:\n%s", written)
	}
}

func TestRunCheckPassesAfterGenerate(t *testing.T) {
	dir := writeTree(t, map[string]string{"AGENTS.src.md": "Body\n\n@x.md\n", "x.md": "X\n"})
	if code, _, se := run(t, dir); code != 0 {
		t.Fatalf("generate failed: %d %s", code, se)
	}
	code, stdout, _ := run(t, dir, "--check")
	if code != 0 {
		t.Errorf("code = %d, want 0; stdout = %q", code, stdout)
	}
	if !strings.Contains(stdout, "up to date") {
		t.Errorf("stdout = %q", stdout)
	}
}

func TestRunCheckFailsWhenStale(t *testing.T) {
	dir := writeTree(t, map[string]string{"AGENTS.src.md": "Body\n\n@x.md\n", "x.md": "X\n"})
	if code, _, se := run(t, dir); code != 0 {
		t.Fatalf("generate failed: %d %s", code, se)
	}
	if err := os.WriteFile(filepath.Join(dir, "AGENTS.src.md"), []byte("CHANGED\n\n@x.md\n"), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
	code, stdout, _ := run(t, dir, "--check")
	if code != 1 {
		t.Errorf("code = %d, want 1", code)
	}
	want := "AGENTS.md is out of date. Run: at-include\n" +
		"First difference around line 11:\n" +
		"  > in `AGENTS.src.md` and regenerate — do not edit this file.\n" +
		"  \n" +
		"- Body\n" +
		"+ CHANGED\n" +
		"  \n" +
		"  Contents of x.md (project instructions, checked into the codebase):\n"
	if stdout != want {
		t.Errorf("stdout = %q, want %q", stdout, want)
	}
}

func TestRunCheckMissingOutputFails(t *testing.T) {
	dir := writeTree(t, map[string]string{"AGENTS.src.md": "Body\n"})
	code, stdout, _ := run(t, dir, "--check")
	if code != 1 {
		t.Errorf("code = %d, want 1", code)
	}
	if !strings.Contains(stdout, "out of date") {
		t.Errorf("stdout = %q", stdout)
	}
}

// TestRunCheckRuntimeErrorGoesToStderr exercises the branch where
// flatten.Check itself returns an error (as opposed to reporting a merely
// stale/missing output) — here, a resolved import chain exceeding
// --max-depth. This must land on stderr, matching the "runtime error" row of
// the CLI's behavior contract, not stdout.
func TestRunCheckRuntimeErrorGoesToStderr(t *testing.T) {
	dir := writeTree(t, map[string]string{"AGENTS.src.md": "@a.md\n", "a.md": "DEEP\n"})
	code, stdout, stderr := run(t, dir, "--check", "--max-depth", "0")
	if code != 1 {
		t.Errorf("code = %d, want 1", code)
	}
	if stdout != "" {
		t.Errorf("stdout should be empty on a runtime error, got %q", stdout)
	}
	if !strings.Contains(stderr, "at-include:") || !strings.Contains(stderr, "depth") {
		t.Errorf("stderr = %q", stderr)
	}
}

func TestRunHelp(t *testing.T) {
	dir := writeTree(t, map[string]string{"AGENTS.src.md": "x\n"})
	for _, flag := range []string{"--help", "-h"} {
		code, stdout, _ := run(t, dir, flag)
		if code != 0 {
			t.Errorf("%s: code = %d, want 0", flag, code)
		}
		if !strings.Contains(stdout, "Usage") {
			t.Errorf("%s: stdout = %q", flag, stdout)
		}
	}
}

func TestRunUnknownFlagIsUsageError(t *testing.T) {
	dir := writeTree(t, map[string]string{"AGENTS.src.md": "x\n"})
	code, _, stderr := run(t, dir, "--bogus")
	if code != 2 {
		t.Errorf("code = %d, want 2", code)
	}
	if !strings.Contains(stderr, "Unknown argument") || !strings.Contains(stderr, "Usage") {
		t.Errorf("stderr = %q", stderr)
	}
}

func TestRunMaxDepth(t *testing.T) {
	files := map[string]string{"AGENTS.src.md": "@a.md\n", "a.md": "@b.md\n", "b.md": "DEEP\n"}

	dir := writeTree(t, files)
	if code, _, se := run(t, dir, "--max-depth", "2"); code != 0 {
		t.Errorf("maxDepth 2: code = %d, want 0; stderr = %q", code, se)
	}

	dir2 := writeTree(t, files)
	code, _, stderr := run(t, dir2, "--max-depth", "1")
	if code != 1 {
		t.Errorf("maxDepth 1: code = %d, want 1", code)
	}
	if !strings.Contains(stderr, "at-include:") || !strings.Contains(stderr, "depth") {
		t.Errorf("stderr = %q", stderr)
	}
}

func TestRunMaxDepthInvalidValues(t *testing.T) {
	dir := writeTree(t, map[string]string{"AGENTS.src.md": "x\n"})
	for _, v := range []string{"notanumber", "", "-1", "1.5"} {
		code, _, stderr := run(t, dir, "--max-depth", v)
		if code != 2 {
			t.Errorf("--max-depth %q: code = %d, want 2", v, code)
		}
		if !strings.Contains(stderr, "non-negative integer") {
			t.Errorf("--max-depth %q: stderr = %q", v, stderr)
		}
	}
	code, _, stderr := run(t, dir, "--max-depth")
	if code != 2 {
		t.Errorf("--max-depth with no value: code = %d, want 2", code)
	}
	if !strings.Contains(stderr, "non-negative integer") {
		t.Errorf("stderr = %q", stderr)
	}
}

func TestRunCustomSrcOutAndRoot(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"docs/CLAUDE.src.md": "Body\n\n@notes.md\n",
		"docs/notes.md":      "NOTES\n",
	})
	code, stdout, stderr := run(t, dir,
		"--src", "docs/CLAUDE.src.md", "--out", "docs/CLAUDE.md", "--root", ".")
	if code != 0 {
		t.Fatalf("code = %d, stderr = %q", code, stderr)
	}
	if !strings.Contains(stdout, "Generated docs/CLAUDE.md") {
		t.Errorf("stdout = %q", stdout)
	}
	written, err := os.ReadFile(filepath.Join(dir, "docs", "CLAUDE.md"))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !strings.Contains(string(written), "Contents of docs/notes.md") {
		t.Errorf("marker should be root-relative:\n%s", written)
	}
	if !strings.Contains(string(written), "CLAUDE.src.md") {
		t.Errorf("banner should name the configured source:\n%s", written)
	}
}

func TestRunMissingSourceIsRuntimeError(t *testing.T) {
	dir := writeTree(t, map[string]string{"other.md": "x\n"})
	code, _, stderr := run(t, dir)
	if code != 1 {
		t.Errorf("code = %d, want 1", code)
	}
	if !strings.Contains(stderr, "at-include:") {
		t.Errorf("stderr = %q", stderr)
	}
}

func TestRunListImports(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"AGENTS.src.md": "@a.md and `@b.md` and @c.md\n",
	})
	code, stdout, stderr := run(t, dir, "--list-imports")
	if code != 0 {
		t.Fatalf("code = %d, stderr = %q", code, stderr)
	}
	if got, want := stdout, "a.md\nc.md\n"; got != want {
		t.Errorf("stdout = %q, want %q", got, want)
	}
	if _, err := os.Stat(filepath.Join(dir, "AGENTS.md")); !os.IsNotExist(err) {
		t.Error("--list-imports must not write the output file")
	}
}

func TestRunVersion(t *testing.T) {
	dir := writeTree(t, map[string]string{"AGENTS.src.md": "x\n"})
	code, stdout, _ := run(t, dir, "--version")
	if code != 0 {
		t.Errorf("code = %d, want 0", code)
	}
	if strings.TrimSpace(stdout) == "" {
		t.Error("--version should print something")
	}
}

func TestRunMarkerDescOverride(t *testing.T) {
	dir := writeTree(t, map[string]string{"AGENTS.src.md": "@x.md\n", "x.md": "X\n"})
	if code, _, se := run(t, dir, "--marker-desc", "custom wording"); code != 0 {
		t.Fatalf("code = %d, stderr = %q", code, se)
	}
	written, err := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !strings.Contains(string(written), "Contents of x.md (custom wording):") {
		t.Errorf("marker desc not applied:\n%s", written)
	}
}

// --- Fix 1: --out must never resolve to the same file as --src ---
//
// This is the DATA LOSS bug: `at-include --out AGENTS.src.md` used to happily
// overwrite the hand-authored source with the generated banner + (now
// self-referential) content, and reported success (exit 0). Every case below
// asserts BOTH the exit code/stderr AND that the source file's bytes are
// completely untouched by the rejected run — a nonzero exit code alone would
// not catch a "partial write before erroring" regression.

func TestRunOutSameAsSrcIsRejected(t *testing.T) {
	const original = "AUTHORED SOURCE\n\n@x.md\n"
	dir := writeTree(t, map[string]string{"AGENTS.src.md": original, "x.md": "X\n"})

	code, stdout, stderr := run(t, dir, "--out", "AGENTS.src.md")
	if code != 2 {
		t.Errorf("code = %d, want 2 (usage error)", code)
	}
	if stdout != "" {
		t.Errorf("stdout should be empty on this usage error, got %q", stdout)
	}
	if !strings.Contains(stderr, "--out") || !strings.Contains(stderr, "--src") {
		t.Errorf("stderr should name both flags, got %q", stderr)
	}
	if !strings.Contains(stderr, "Usage") {
		t.Errorf("stderr should include usage text like other usage errors, got %q", stderr)
	}

	after, err := os.ReadFile(filepath.Join(dir, "AGENTS.src.md"))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if string(after) != original {
		t.Errorf("source file was modified by the rejected run: got %q, want %q", after, original)
	}
}

func TestRunOutSameAsSrcDifferentSpellingIsRejected(t *testing.T) {
	const original = "AUTHORED SOURCE\n\n@x.md\n"
	dir := writeTree(t, map[string]string{"AGENTS.src.md": original, "x.md": "X\n"})

	// "./AGENTS.src.md" resolves to the same absolute path as the default
	// --src "AGENTS.src.md", via a different spelling than a bare Clean
	// no-op comparison of the raw strings would catch trivially — this
	// exercises the filepath.Abs + filepath.Clean normalization, not just an
	// exact string match.
	code, _, stderr := run(t, dir, "--out", "./AGENTS.src.md")
	if code != 2 {
		t.Errorf("code = %d, want 2", code)
	}
	if !strings.Contains(stderr, "--out") {
		t.Errorf("stderr = %q", stderr)
	}

	after, err := os.ReadFile(filepath.Join(dir, "AGENTS.src.md"))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if string(after) != original {
		t.Errorf("source file was modified by the rejected run: got %q, want %q", after, original)
	}
}

func TestRunOutSymlinkToSrcIsRejected(t *testing.T) {
	const original = "AUTHORED SOURCE\n\n@x.md\n"
	dir := writeTree(t, map[string]string{"AGENTS.src.md": original, "x.md": "X\n"})
	if err := os.Symlink(filepath.Join(dir, "AGENTS.src.md"), filepath.Join(dir, "link.md")); err != nil {
		t.Fatalf("Symlink: %v", err)
	}

	code, _, stderr := run(t, dir, "--out", "link.md")
	if code != 2 {
		t.Errorf("code = %d, want 2", code)
	}
	if !strings.Contains(stderr, "--out") {
		t.Errorf("stderr = %q", stderr)
	}

	after, err := os.ReadFile(filepath.Join(dir, "AGENTS.src.md"))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if string(after) != original {
		t.Errorf("source file was modified by the rejected run: got %q, want %q", after, original)
	}
}

func TestRunOutDifferentFromSrcStillWorks(t *testing.T) {
	// Sanity check alongside the rejection tests above: an --out that merely
	// happens to share a directory (or a name prefix) with --src, but is not
	// actually the same file, must still generate normally.
	dir := writeTree(t, map[string]string{"AGENTS.src.md": "Body\n\n@x.md\n", "x.md": "X\n"})
	code, _, stderr := run(t, dir, "--out", "AGENTS.src.md.generated")
	if code != 0 {
		t.Fatalf("code = %d, stderr = %q", code, stderr)
	}
	if _, err := os.Stat(filepath.Join(dir, "AGENTS.src.md.generated")); err != nil {
		t.Errorf("expected output file to be written: %v", err)
	}
}

// --- Fix 2: regenCommand must print a command that, run from the caller's
// CWD, actually regenerates the right files and makes --check pass. ---

func TestRegenCommandDefaults(t *testing.T) {
	got := regenCommand(options{src: defaultSrc, out: defaultOut})
	want := "at-include"
	if got != want {
		t.Errorf("regenCommand = %q, want %q", got, want)
	}
}

func TestRegenCommandSubdirectorySrc(t *testing.T) {
	// This is the bug as reported: --src/--out under docs/ must appear in the
	// suggestion exactly as the user typed them (CWD-relative), not collapsed
	// to root-relative display names that happen to omit the docs/ prefix.
	got := regenCommand(options{
		src: "docs/CLAUDE.src.md",
		out: "docs/CLAUDE.md",
	})
	want := "at-include --src docs/CLAUDE.src.md --out docs/CLAUDE.md"
	if got != want {
		t.Errorf("regenCommand = %q, want %q", got, want)
	}
}

func TestRegenCommandEmitsRoot(t *testing.T) {
	// With --root explicitly set (even to "."), the suggestion must include
	// it: omitting --root here means the regenerated markers resolve against
	// a different root than the one --check actually used, so following the
	// printed command would NOT make --check pass.
	got := regenCommand(options{
		src: defaultSrc, out: defaultOut,
		root: ".", rootSet: true,
	})
	want := "at-include --root ."
	if got != want {
		t.Errorf("regenCommand = %q, want %q", got, want)
	}
}

func TestRegenCommandAllFlags(t *testing.T) {
	got := regenCommand(options{
		src: "docs/CLAUDE.src.md", out: "docs/CLAUDE.md",
		root: "docs", rootSet: true,
		maxDepth: 5, maxDepthSet: true,
		markerDesc: "custom wording", markerDescSet: true,
	})
	want := "at-include --src docs/CLAUDE.src.md --out docs/CLAUDE.md --root docs --max-depth 5 --marker-desc 'custom wording'"
	if got != want {
		t.Errorf("regenCommand = %q, want %q", got, want)
	}
}

func TestRegenCommandExplicitEmptyMarkerDesc(t *testing.T) {
	// An explicitly-passed `--marker-desc ""` must still be echoed (as `''`),
	// distinguishing it from "not passed" — this is what markerDescSet is for.
	got := regenCommand(options{
		src: defaultSrc, out: defaultOut,
		markerDesc: "", markerDescSet: true,
	})
	want := "at-include --marker-desc ''"
	if got != want {
		t.Errorf("regenCommand = %q, want %q", got, want)
	}
}

// TestRunCheckSuggestionRoundTrips is the end-to-end guarantee behind Fix 2:
// generate into a subdirectory with an explicit --root, go stale, run
// --check, and confirm that running the EXACT command printed after "Run: "
// (parsed the same way argv normally would be) makes a follow-up --check
// pass. This is what "the suggestion actually works" means operationally.
func TestRunCheckSuggestionRoundTrips(t *testing.T) {
	dir := writeTree(t, map[string]string{
		"docs/CLAUDE.src.md": "Body\n\n@notes.md\n",
		"docs/notes.md":      "NOTES\n",
	})
	argv := []string{"--src", "docs/CLAUDE.src.md", "--out", "docs/CLAUDE.md", "--root", "."}
	if code, _, se := run(t, dir, argv...); code != 0 {
		t.Fatalf("initial generate failed: %d %s", code, se)
	}
	if err := os.WriteFile(filepath.Join(dir, "docs", "CLAUDE.src.md"), []byte("CHANGED\n\n@notes.md\n"), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	code, stdout, stderr := run(t, dir, "--check", "--src", "docs/CLAUDE.src.md", "--out", "docs/CLAUDE.md", "--root", ".")
	if code != 1 {
		t.Fatalf("--check should fail while stale: code = %d, stderr = %q", code, stderr)
	}
	const prefix = "docs/CLAUDE.md is out of date. Run: "
	if !strings.HasPrefix(stdout, prefix) {
		t.Fatalf("stdout = %q, want prefix %q", stdout, prefix)
	}
	rest := strings.TrimPrefix(stdout, prefix)
	suggestedLine, _, _ := strings.Cut(rest, "\n")
	wantSuggestion := "at-include --src docs/CLAUDE.src.md --out docs/CLAUDE.md --root ."
	if suggestedLine != wantSuggestion {
		t.Fatalf("suggested command = %q, want %q", suggestedLine, wantSuggestion)
	}

	suggestedArgv := strings.Fields(suggestedLine)[1:] // drop the leading "at-include"
	if code, _, se := run(t, dir, suggestedArgv...); code != 0 {
		t.Fatalf("following the suggested command failed: %d %s", code, se)
	}

	// The suggested command's argv plus --check must now report up to date.
	checkArgv := append(append([]string{}, suggestedArgv...), "--check")
	code, stdout, stderr = run(t, dir, checkArgv...)
	if code != 0 {
		t.Fatalf("--check after following the suggestion should pass: code = %d, stdout = %q, stderr = %q", code, stdout, stderr)
	}
	if !strings.Contains(stdout, "up to date") {
		t.Errorf("stdout = %q", stdout)
	}
}

// --- Fix 4: shellQuote must produce output that is actually safe to paste
// into a POSIX shell, not just visually plausible. ---

func TestShellQuote(t *testing.T) {
	cases := []struct{ in, want string }{
		{"plain", "plain"},
		{"has spaces", "'has spaces'"},
		{`has "quotes" and $dollar`, `'has "quotes" and $dollar'`},
		{"has'single'quotes", `'has'\''single'\''quotes'`},
		{"has`backtick`", "'has`backtick`'"},
		{"has!bang", "'has!bang'"},
		{"", "''"},
	}
	for _, c := range cases {
		if got := shellQuote(c.in); got != c.want {
			t.Errorf("shellQuote(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

// TestShellQuoteRoundTripsThroughShell is the load-bearing assertion behind
// Fix 4: actually run the quoted output through /bin/sh and confirm the value
// comes back out byte-for-byte, for values containing every metacharacter the
// old strconv.Quote-based quoteArg mishandled (in particular "$", which
// double-quoting leaves live for shell expansion).
func TestShellQuoteRoundTripsThroughShell(t *testing.T) {
	if _, err := exec.LookPath("sh"); err != nil {
		t.Skip("no /bin/sh available")
	}
	cases := []string{
		`has "quotes" and $dollar`,
		"has'single'quotes",
		"has`backtick`and$var",
		"has!bang and $HOME",
		"plain",
		"",
		`mix of ' and " and $ and ` + "`",
	}
	for _, in := range cases {
		quoted := shellQuote(in)
		cmd := exec.Command("sh", "-c", "printf '%s' "+quoted)
		out, err := cmd.Output()
		if err != nil {
			t.Fatalf("sh -c failed for input %q (quoted %q): %v", in, quoted, err)
		}
		if string(out) != in {
			t.Errorf("round-trip through sh: input %q, quoted %q, got back %q", in, quoted, string(out))
		}
	}
}
